# Generated by Django 5.0.6 on 2024-05-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("pathway", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="student_images/")),
                ("project_poster", models.ImageField(upload_to="project_posters/")),
                ("bio", models.TextField()),
            ],
        ),
    ]
